spring.config.import=optional:file:../.env[.properties]
spring.application.name=${TASK_MANAGER_BUSINESS_SERVICE_NAME:task_manager_business_service}
server.port=${TASK_MANAGER_BUSINESS_SERVICE_PORT:8082}

spring.datasource.url=${TASK_MANAGER_BUSINESS_DB_URL:jdbc:mysql://localhost:3306/task_manager_business?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${TASK_MANAGER_BUSINESS_DB_USERNAME:root}
spring.datasource.password=${TASK_MANAGER_BUSINESS_DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update

spring.output.ansi.enabled=always

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
