spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: ${EUREKA_SERVER_NAME:eureka-server}

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
