spring.config.import=optional:file:../.env[.properties]
spring.application.name=${AUTH_SERVICE_NAME:auth-service}
server.port=${AUTH_SERVICE_PORT:8084}

spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/auth_service?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${AUTH_DB_USERNAME:root}
spring.datasource.password=${AUTH_DB_PASSWORD:password}

spring.output.ansi.enabled=always

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}



